/* ============================================================
   AI ANIMATION AUTOMATION — app.js (Google AI Studio Edition)
   Pipeline: Google Gemini Story → Fal.ai Images → Runway ML Videos
   ============================================================ */

const STATE = {
  googleKey: '',
  falKey: '',
  runwayKey: '',
  storyInput: '',
  imageStyle: '',
  sceneCount: 8,
  generatedStory: null,
  generatedImages: [],
  generatedVideos: [],
  currentVideoIndex: 0,
};

const $ = id => document.getElementById(id);

// Init and Key management
(function init() {
  const saved = {
    google: localStorage.getItem('aaa_google') || '',
    fal: localStorage.getItem('aaa_fal') || '',
    runway: localStorage.getItem('aaa_runway') || ''
  };
  
  if (saved.google && saved.fal && saved.runway) {
    STATE.googleKey = saved.google;
    STATE.falKey = saved.fal;
    STATE.runwayKey = saved.runway;
    $('googleKey').value = saved.google;
    $('falKey').value = saved.fal;
    $('runwayKey').value = saved.runway;
    $('apiModal').classList.add('hidden');
  }

  $('saveKeys').addEventListener('click', () => {
    const g = $('googleKey').value.trim();
    const f = $('falKey').value.trim();
    const r = $('runwayKey').value.trim();
    if (!g || !f || !r) return alert('API Keys from Google AI Studio, Fal, and Runway are required.');
    
    STATE.googleKey = g; 
    STATE.falKey = f; 
    STATE.runwayKey = r;
    
    localStorage.setItem('aaa_google', g);
    localStorage.setItem('aaa_fal', f);
    localStorage.setItem('aaa_runway', r);
    $('apiModal').classList.add('hidden');
  });

  $('generateStoryBtn').addEventListener('click', handleGenerateStory);
  $('generateImagesBtn').addEventListener('click', handleGenerateImages);
  $('generateVideosBtn').addEventListener('click', handleGenerateVideos);
})();

async function handleGenerateStory() {
  const text = $('storyInput').value.trim();
  if (!text) return;
  STATE.storyInput = text;
  STATE.sceneCount = parseInt($('sceneCount').value);
  STATE.imageStyle = $('imageStyle').value;

  $('pipelineTrack').style.display = 'block';
  log('Generating story with Google AI Studio (Gemini)...', 'info');

  try {
    const story = await generateStoryGoogleAI(text, STATE.sceneCount, STATE.imageStyle);
    STATE.generatedStory = story;
    renderStoryReview(story);
    $('step1').style.display = 'none';
    $('step2').style.display = 'block';
    log('✓ Story generated by Google AI Studio', 'success');
  } catch (err) {
    log('✗ Google AI Studio Error: ' + err.message, 'err');
  }
}

async function generateStoryGoogleAI(userInput, sceneCount, style) {
  const prompt = `You are a master storyteller. Expand the following outline into exactly ${sceneCount} scenes.
Respond ONLY with valid JSON in this structure:
{
  "title": "Story Title",
  "synopsis": "One paragraph synopsis",
  "scenes": [
    {
      "num": 1,
      "title": "Scene Title",
      "narrative": "3-5 sentences of narrative",
      "imagePrompt": "Detailed AI image prompt in ${style} style. Cinematic lighting."
    }
  ]
}
Outline: ${userInput}`;

  // Use Google AI Studio / Gemini 1.5 Flash endpoint
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${STATE.googleKey}`;
  
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { 
        response_mime_type: "application/json", 
        temperature: 0.85 
      }
    })
  });

  if (!res.ok) {
    const errData = await res.json();
    throw new Error(errData.error?.message || 'Google API Error');
  }

  const data = await res.json();
  // Parsing the JSON string returned by Gemini
  return JSON.parse(data.candidates[0].content.parts[0].text);
}

function renderStoryReview(story) {
  $('storyTitle').textContent = story.title;
  $('scenesContainer').innerHTML = story.scenes.map(s => `
    <div class="scene-card">
      <strong>Scene ${s.num}: ${s.title}</strong>
      <p>${s.narrative}</p>
      <small style="color:var(--accent)">Prompt: ${s.imagePrompt}</small>
    </div>
  `).join('');
}

async function handleGenerateImages() {
  log('Generating images with Fal.ai...', 'info');
  STATE.generatedImages = [];
  $('step2').style.display = 'none';
  $('step3').style.display = 'block';
  $('imageGrid').innerHTML = '';
  
  for (const scene of STATE.generatedStory.scenes) {
    try {
      const url = await generateImageFal(scene.imagePrompt);
      STATE.generatedImages.push({ sceneNum: scene.num, url });
      const img = document.createElement('div');
      img.className = 'image-card';
      img.innerHTML = `<img src="${url}"><div style="padding:5px;font-size:10px">Scene ${scene.num}</div>`;
      $('imageGrid').appendChild(img);
      log(`✓ Image ${scene.num} ready`, 'success');
    } catch (e) { 
      log(`✗ Image ${scene.num} failed`, 'err'); 
    }
  }
}

async function generateImageFal(prompt) {
  const res = await fetch('https://fal.run/fal-ai/flux/schnell', {
    method: 'POST',
    headers: { 
      'Content-Type': 'application/json', 
      'Authorization': `Key ${STATE.falKey}` 
    },
    body: JSON.stringify({ 
      prompt, 
      image_size: 'landscape_16_9', 
      num_inference_steps: 4 
    })
  });
  if (!res.ok) throw new Error('Fal.ai API Error');
  const data = await res.json();
  return data.images[0].url;
}

async function handleGenerateVideos() {
  log('Animating with Runway ML...', 'info');
  log('Video generation started (logic would go here)...', 'info');
  $('step3').style.display = 'none';
  $('step4').style.display = 'block';
}

function log(msg, type) {
  const p = document.createElement('div');
  p.textContent = `[${new Date().toLocaleTimeString()}] ${msg}`;
  if(type === 'err') p.style.color = '#ff6666';
  if(type === 'success') p.style.color = '#88ff88';
  $('pipelineLog').appendChild(p);
  $('pipelineLog').scrollTop = $('pipelineLog').scrollHeight;
}